### PR TITLE
Add docker-compose examples for OCR setup

### PR DESCRIPTION
**Pull request by yuya-kitani**
Add docker-compose examples for OCR setup

### CODE REVIEW

**Review by bryanbellsmith — APPROVED** [review]
This looks great! Thanks Yuya!

**Review by letmerecall — APPROVED** [review]
Look good!

**Comment by yuya-kitani** [comment]
Thank you both!!

**Comment by letmerecall** [comment]
@yuya-kitani, I just saw https://github.com/privateai/redocly-docs/pull/362 and realized that we removed the examples from there. I prefer we add sample YAML files instead of having it in a markdown. This can be a separate ticket.

**Comment by letmerecall** [comment]
Sorry but one more comment, I'm not sure why we decided to put this under `python` directory. It's not language dependent and putting it under python is making it's discovery hard.

**Comment by yuya-kitani** [comment]
Thanks @letmerecall ! I will make a new ticket to adjust them!

**Pull request merged**
